import { useState, useEffect, useRef, useMemo } from 'react';
import { useFetcher } from '@remix-run/react';
import type { Character, ScenarioForDisplay, PlayerSlot, AdventureScenario, DiceRollingState } from '~/types';
import { useGlobalToast } from '~/utils/toast';
import { subscribeToRoomChanges } from '~/services/realtime.client';
import DiceRoller3D from './DiceRoller3D';


interface ScenarioSelectorProps {
  scenarios: ScenarioForDisplay[] | null;
  isLoading: boolean; 
  activeCharacter: Character | null;
  showCountdown?: boolean;
  partyCharacters?: Character[];
  partySlots?: PlayerSlot[];
  currentUserId?: string;
  roomCode?: string | null;
  isHost?: boolean; // NEW: Track if current user is the host
}

export default function ScenarioSelector({ scenarios, isLoading, activeCharacter, showCountdown: initialShowCountdown, partyCharacters = [], partySlots = [], currentUserId = '', roomCode: initialRoomCode = null, isHost = false }: ScenarioSelectorProps) {
  const { showToast } = useGlobalToast();
  
  // State for scenario suggestions from database
  const [recentSuggestions, setRecentSuggestions] = useState<Array<{
    id: string;
    user_id: string;
    username: string;
    message: string;
    created_at: string;
  }>>([]);
  const [lastSuggestionTime, setLastSuggestionTime] = useState<number>(0);
  const [lastSeenSuggestionId, setLastSeenSuggestionId] = useState<string | null>(null);
  const [lastToastSuggestionId, setLastToastSuggestionId] = useState<string | null>(null);
  const [lastToastTime, setLastToastTime] = useState<number>(0);
  const hasInitializedRef = useRef(false);
  const hasShownToastForCurrentSuggestion = useRef(false);
  const lastProcessedSuggestionId = useRef<string | null>(null);
  
  console.log(`[SCENARIO SELECTOR] Props received:`, {
    isHost,
    roomCode: initialRoomCode,
    currentUserId,
    partySlots: partySlots.map(s => ({ type: s.type, characterId: s.characterId, userId: s.userId })),
    scenarios: scenarios?.length || 0,
    activeCharacter: activeCharacter ? { id: activeCharacter.id, name: activeCharacter.name } : null
  });
  
  // Check if activeCharacter is missing and show error
  useEffect(() => {
    if (!activeCharacter) {
      console.warn(`[SCENARIO SELECTOR] Active character is missing! This will prevent scenario generation.`);
      showToast('Active character data is missing. Cannot generate scenarios.', 'error');
    }
  }, [activeCharacter, showToast]);

  // Initialize lastSeenSuggestionId from localStorage when roomCode is available
  useEffect(() => {
    if (typeof window !== 'undefined' && initialRoomCode && !hasInitializedRef.current) {
      const savedSeenId = localStorage.getItem(`lastSeenSuggestionId_${initialRoomCode}`);
      const savedToastId = localStorage.getItem(`lastToastSuggestionId_${initialRoomCode}`);
      
      if (savedSeenId) {
        setLastSeenSuggestionId(savedSeenId);
        lastProcessedSuggestionId.current = savedSeenId;
        console.log(`[SCENARIO SELECTOR] Initialized lastSeenSuggestionId from localStorage: ${savedSeenId}`);
      }
      
      if (savedToastId) {
        setLastToastSuggestionId(savedToastId);
        console.log(`[SCENARIO SELECTOR] Initialized lastToastSuggestionId from localStorage: ${savedToastId}`);
      }
      
      // Reset toast flag on initialization
      hasShownToastForCurrentSuggestion.current = false;
      console.log(`[SCENARIO SELECTOR] Reset toast flag on initialization`);
      
      hasInitializedRef.current = true;
    }
  }, [initialRoomCode]);
  const fetcher = useFetcher<any>();
  const voteFetcher = useFetcher<any>();
  const scenarioFetcher = useFetcher<any>();
  const [selectedDuration, setSelectedDuration] = useState<string>('Short');
  const [customPrompt, setCustomPrompt] = useState<string>('');
  const [displayedScenarios, setDisplayedScenarios] = useState<ScenarioForDisplay[] | null>(scenarios);
  const [showCountdown, setShowCountdown] = useState(initialShowCountdown || false);
  const [countdown, setCountdown] = useState(5);
  const [scenarioVotes, setScenarioVotes] = useState<Record<string, number>>({});
  const [userVotes, setUserVotes] = useState<Record<number, string | null>>({});
  const [regenerationVotes, setRegenerationVotes] = useState<number>(0);
  const [autoGeneratedOnce, setAutoGeneratedOnce] = useState(false);
  const [roomCode, setRoomCode] = useState<string | null>(initialRoomCode);
  const [showDiceRoll, setShowDiceRoll] = useState(false);
  const [diceRolls, setDiceRolls] = useState<Record<number, number>>({});
  const [diceRollComplete, setDiceRollComplete] = useState(false);
  const [lastVoteTime, setLastVoteTime] = useState<string>('');
  
  const rollIntervalRef = useRef<NodeJS.Timeout | null>(null);

  const isGenerating = fetcher.state !== 'idle';
  const activePartyMembers = partyCharacters.filter(c => c);
  
  // Real-time dice rolling state
  const [diceState, setDiceState] = useState<DiceRollingState | null>(null);
  const [isInitializingDice, setIsInitializingDice] = useState(false);
  const [isSubmittingRoll, setIsSubmittingRoll] = useState(false);
  
  // Calculate how many active slots the current user controls
  const userActiveSlots = partySlots.filter(slot => 
    (slot.type === 'Human' || slot.type === 'AI') && slot.userId === currentUserId
  ).length;
  
  // Calculate total active slots across all party
  const totalActiveSlots = partySlots.filter(slot => 
    slot.type === 'Human' || slot.type === 'AI'
  ).length;
  
  // Get the indices of slots owned by the current user for voting
  const userSlotIndices = partySlots
    .map((slot, index) => ({ slot, index }))
    .filter(({ slot }) => (slot.type === 'Human' || slot.type === 'AI') && slot.userId === currentUserId)
    .map(({ index }) => index);
  
  // Count votes cast by current user
  const userVotesCast = Object.values(userVotes).filter(v => v !== null).length;

  const handleStartCountdown = () => {
    setShowCountdown(true);
    setCountdown(5);
  };

  // Auto-generate scenarios on first load when in countdown mode
  useEffect(() => {
    if (showCountdown && !autoGeneratedOnce && !displayedScenarios && !isGenerating && activeCharacter) {
      setAutoGeneratedOnce(true);
      // Automatically generate scenarios after countdown
      const timer = setTimeout(() => {
        triggerAutoGenerate();
      }, 5500); // Wait for countdown to finish
      return () => clearTimeout(timer);
    }
  }, [showCountdown, autoGeneratedOnce, displayedScenarios, isGenerating, activeCharacter]);

  const triggerAutoGenerate = () => {
    if (!activeCharacter) return;
    const formData = new FormData();
    formData.append('intent', 'generateScenarios');
    formData.append('duration', selectedDuration);
    formData.append('activeCharacter', JSON.stringify(activeCharacter));
    formData.append('partyCharacters', JSON.stringify(partyCharacters));
    formData.append('partySlots', JSON.stringify(partySlots));
    fetcher.submit(formData, { method: 'post', action: '/game' });
  };

  // Subscribe to real-time dice state changes
  useEffect(() => {
    if (!roomCode) return;
    
    const unsubscribe = subscribeToRoomChanges(roomCode, (payload) => {
      const newDiceState = payload.new.dice_rolling_state;
      if (newDiceState) {
        setDiceState(newDiceState);
        // Update local diceRolls state for UI display
        setDiceRolls(newDiceState.rolls || {});
        // Check if complete
        if (newDiceState.status === 'completed') {
          setDiceRollComplete(true);
        }
        
        // Show dice rolling UI when dice state is rolling
        if (newDiceState.status === 'rolling' && newDiceState.players.length > 0) {
          setShowDiceRoll(true);
        } else if (newDiceState.status === 'not-started' || !newDiceState.players || newDiceState.players.length === 0) {
          setShowDiceRoll(false);
        }
      }
    });
    
    return () => unsubscribe();
  }, [roomCode]);

  // Initial fetch for dice rolling state when roomCode is available
  useEffect(() => {
    if (!roomCode) return;
    
    const fetchInitialDiceState = async () => {
      try {
        const formData = new FormData();
        formData.append('intent', 'getDiceRollingState');
        formData.append('roomCode', roomCode);
        
        const response = await fetch('/api/room/dice', {
          method: 'POST',
          body: formData
        });
        
        const result = await response.json();
        
        if (result.success && result.diceRollingState) {
          setDiceState(result.diceRollingState);
          setDiceRolls(result.diceRollingState.rolls || {});
          
          // Show dice UI if there's an active rolling state
          if (result.diceRollingState.status === 'rolling' && result.diceRollingState.players.length > 0) {
            setShowDiceRoll(true);
          }
        }
      } catch (error) {
        console.error('Error fetching initial dice state:', error);
      }
    };
    
    fetchInitialDiceState();
  }, [roomCode]);

  // Countdown effect
  useEffect(() => {
    if (!showCountdown) return;

    if (countdown === 0) {
      setShowCountdown(false);
      setCountdown(5);
      return;
    }

    const timer = setTimeout(() => {
      setCountdown(countdown - 1);
    }, 1000);

    return () => clearTimeout(timer);
  }, [showCountdown, countdown]);

  const handleVoteScenario = (slotIndex: number, scenarioId: string) => {
    // Only allow voting for slots owned by current user
    if (!userSlotIndices.includes(slotIndex)) {
      console.log(`[VOTING] Cannot vote for slot ${slotIndex} - not owned by current user`);
      return;
    }
    
    // Get user information for the vote
    const slot = partySlots[slotIndex];
    const username = slot.username || `Player ${slotIndex}`;
    
    setUserVotes(prev => {
      const newVotes = { ...prev };
      const previousVote = newVotes[slotIndex];
      
      if (previousVote === scenarioId) {
        // Retract vote
        delete newVotes[slotIndex];
        setScenarioVotes(prevVotes => ({
          ...prevVotes,
          [scenarioId]: (prevVotes[scenarioId] || 1) - 1
        }));
      } else {
        // Change or cast new vote
        if (previousVote) {
          setScenarioVotes(prevVotes => ({
            ...prevVotes,
            [previousVote]: (prevVotes[previousVote] || 1) - 1
          }));
        }
        newVotes[slotIndex] = scenarioId;
        setScenarioVotes(prevVotes => ({
          ...prevVotes,
          [scenarioId]: (prevVotes[scenarioId] || 0) + 1
        }));
      }
      return newVotes;
    });
    
    // Submit vote to server for real-time updates
    if (roomCode) {
      const formData = new FormData();
      formData.append('intent', 'castVote');
      formData.append('scenarioId', scenarioId);
      formData.append('slotIndex', slotIndex.toString());
      formData.append('roomCode', roomCode);
      formData.append('username', username);
      formData.append('userId', currentUserId || 'unknown');
      formData.append('partySlots', JSON.stringify(partySlots));
      formData.append('scenarioSetId', roomCode); // Use roomCode as scenarioSetId for now
      
      console.log(`[VOTING] Submitting vote for scenario ${scenarioId} from slot ${slotIndex} in room ${roomCode}`);
      voteFetcher.submit(formData, { method: 'post', action: '/game' });
      
      // Also log the fetcher state
      console.log(`[VOTING] VoteFetcher state:`, voteFetcher.state);
      console.log(`[VOTING] VoteFetcher data:`, voteFetcher.data);
    }
  };

  const handleVoteRegenerate = (slotIndex: number) => {
    // Only allow voting for slots owned by current user
    if (!userSlotIndices.includes(slotIndex)) {
      console.log(`[VOTING] Cannot vote for slot ${slotIndex} - not owned by current user`);
      return;
    }
    
    // Get user information for the vote
    const slot = partySlots[slotIndex];
    const username = slot.username || `Player ${slotIndex}`;
    
    setUserVotes(prev => {
      const newVotes = { ...prev };
      const previousVote = newVotes[slotIndex];
      
      if (previousVote === 'REGENERATE') {
        // Retract regenerate vote
        delete newVotes[slotIndex];
        setRegenerationVotes(prev => prev - 1);
      } else {
        // Change vote to regenerate
        if (previousVote) {
          setScenarioVotes(prevVotes => ({
            ...prevVotes,
            [previousVote]: (prevVotes[previousVote] || 1) - 1
          }));
        }
        newVotes[slotIndex] = 'REGENERATE';
        setRegenerationVotes(prev => prev + 1);
      }
      return newVotes;
    });
    
    // Submit regenerate vote to server for real-time updates
    if (roomCode) {
      const formData = new FormData();
      formData.append('intent', 'castVote');
      formData.append('scenarioId', 'REGENERATE'); // Special scenario ID for regenerate
      formData.append('slotIndex', slotIndex.toString());
      formData.append('roomCode', roomCode);
      formData.append('username', username);
      formData.append('userId', currentUserId || 'unknown');
      formData.append('partySlots', JSON.stringify(partySlots));
      formData.append('scenarioSetId', roomCode); // Use roomCode as scenarioSetId for now
      
      voteFetcher.submit(formData, { method: 'post', action: '/game' });
    }
  };

  const userHasCompletedVoting = userVotesCast >= userActiveSlots;
  const totalVotesCast = Object.values(scenarioVotes).reduce((a, b) => a + b, 0) + regenerationVotes;
  const regenerateVoteCount = regenerationVotes;
  const allHaveVoted = totalVotesCast >= totalActiveSlots;

  // Scenario suggestion handlers
  const handleSuggestScenario = () => {
    // Use the content from the custom prompt field instead of a separate modal
    const suggestionText = customPrompt.trim();
    
    if (!suggestionText) {
      alert("Please enter a scenario suggestion in the custom theme field above.");
      return;
    }

    // Send suggestion to server to notify other users in the room
    // Toast will appear for ALL users (including sender) when fetched via polling
    if (roomCode) {
      const formData = new FormData();
      formData.append('intent', 'broadcastSuggestion');
      formData.append('roomCode', roomCode);
      formData.append('suggestion', suggestionText);
      formData.append('userId', currentUserId || 'unknown');
      
      // Get username from party slots
      const username = partySlots.find(slot => slot.userId === currentUserId)?.username || 'Unknown Player';
      formData.append('username', username);
      
      // Submit to server to broadcast to other users
      fetcher.submit(formData, { method: 'post', action: '/game' });
    }
    
    // Clear the suggestion field after sending
    setCustomPrompt('');
  };
  const regenerateMajority = regenerateVoteCount > totalVotesCast / 2;

  const handleTiebreakerDiceRoll = async () => {
    if (!roomCode) return;
    
    try {
      setIsInitializingDice(true);
      
      // Call API to start dice rolling
      const formData = new FormData();
      formData.append('intent', 'startDiceRolling');
      formData.append('roomCode', roomCode);
      
      const response = await fetch('/api/room/dice', {
        method: 'POST',
        body: formData
      });
      
      const result = await response.json();
      
      if (result.success) {
        setShowDiceRoll(true);
        showToast('Dice rolling started! All players can now roll.', 'success');
      } else {
        showToast('Failed to start dice rolling. Please try again.', 'error');
      }
    } catch (error) {
      console.error('Error starting dice rolling:', error);
      showToast('Failed to start dice rolling. Please try again.', 'error');
    } finally {
      setIsInitializingDice(false);
    }
  };

  // Determine winning scenario from dice roll
  const getWinningScenarioFromDiceRoll = () => {
    if (!diceState || diceState.status !== 'completed') return null;
    
    let winnerSlotIndex = -1;
    
    if (diceState && diceState.winner !== null) {
      winnerSlotIndex = diceState.winner;
    }
    
    const winnerVote = userVotes[winnerSlotIndex];
    const winningScenario = currentScenarios?.find(s => s.id === winnerVote);
    return winningScenario;
  };

  const onPlayerRollComplete = async (slotIndex: number, result: number) => {
    if (!roomCode) return;
    
    try {
      setIsSubmittingRoll(true);
      
      // Optimistic update
      setDiceRolls(prev => ({ ...prev, [slotIndex]: result }));
      
      // Call API to record the roll
      const formData = new FormData();
      formData.append('intent', 'rollDice');
      formData.append('roomCode', roomCode);
      formData.append('slotIndex', slotIndex.toString());
      formData.append('diceResult', result.toString());
      formData.append('diceType', 'd20');
      
      const response = await fetch('/api/room/dice', {
        method: 'POST',
        body: formData
      });
      
      const resultData = await response.json();
      
      if (!resultData.success) {
        // Revert optimistic update on error
        setDiceRolls(prev => {
          const newRolls = { ...prev };
          delete newRolls[slotIndex];
          return newRolls;
        });
        showToast('Failed to record dice roll. Please try again.', 'error');
      }
    } catch (error) {
      console.error('Error recording dice roll:', error);
      showToast('Failed to record dice roll. Please try again.', 'error');
    } finally {
      setIsSubmittingRoll(false);
    }
  };

  const handleSelectScenario = (scenario: ScenarioForDisplay) => {
    if (!activeCharacter) {
      alert("Active character data is missing. Cannot start game.");
      return;
    }

    // If roomCode is provided, submit to world-map route to update room status
    if (roomCode) {
      const formData = new FormData();
      formData.append('intent', 'startGame');
      formData.append('roomCode', roomCode);
      formData.append('selectedScenarioId', scenario.id);
      scenarioFetcher.submit(formData, { method: 'post', action: '/world-map' });
      return;
    }

    // Otherwise, use the original game route logic
    const formData = new FormData();
    formData.append('intent', 'selectScenario');
    formData.append('activeCharacter', JSON.stringify(activeCharacter));
    formData.append('selectedScenario', JSON.stringify(scenario)); 
    scenarioFetcher.submit(formData, { method: 'post', action: '/game' });
  };

  const handleDurationChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedDuration(e.target.value);
  };

  useEffect(() => {
    if (fetcher.data && fetcher.data.scenarios && fetcher.state === 'idle') {
      setDisplayedScenarios(fetcher.data.scenarios);
      // Reset voting when new scenarios are generated
      setUserVotes({});
      setScenarioVotes({});
      setRegenerationVotes(0);
    }
  }, [fetcher.data, fetcher.state]);

  const currentScenarios = displayedScenarios;
  
  // Poll for new suggestions every 3 seconds
  useEffect(() => {
    if (!initialRoomCode) return;
    
    // Reset toast flag when room code changes
    hasShownToastForCurrentSuggestion.current = false;
    console.log(`[SCENARIO SELECTOR] Reset toast flag for new room: ${initialRoomCode}`);
    
    console.log(`[SCENARIO SELECTOR] Starting polling for room ${initialRoomCode}`);
    
    const interval = setInterval(async () => {
      try {
        console.log(`[SCENARIO SELECTOR] Polling for suggestions in room ${initialRoomCode}`);
        const response = await fetch(`/api/room/suggestions?roomCode=${encodeURIComponent(initialRoomCode)}`);
        console.log(`[SCENARIO SELECTOR] Polling response status: ${response.status}`);
        
        if (response.ok) {
          const data = await response.json();
          const newSuggestions = data.suggestions || [];
          
          console.log(`[SCENARIO SELECTOR] Current lastSeenSuggestionId: ${lastSeenSuggestionId}, New suggestions: ${newSuggestions.length}`);
          
          // Check if we have new suggestions and show toast for all users
          if (newSuggestions.length > 0) {
            const newSuggestion = newSuggestions[0]; // Get the most recent suggestion
            
            console.log(`[SCENARIO SELECTOR] Checking suggestion ID: ${newSuggestion.id} vs lastSeen: ${lastSeenSuggestionId}, lastToast: ${lastToastSuggestionId}, lastProcessed: ${lastProcessedSuggestionId.current}`);
            console.log(`[SCENARIO SELECTOR] New suggestion details:`, {
              id: newSuggestion.id,
              message: newSuggestion.message,
              username: newSuggestion.username,
              createdAt: newSuggestion.created_at,
              userId: newSuggestion.user_id,
              currentUserId: currentUserId,
              isHost: isHost
            });
            
            // Check if we have a genuinely new suggestion by comparing IDs
            const isNewSuggestion = newSuggestion.id !== lastProcessedSuggestionId.current;
            
            // Only show toast if this is a truly new suggestion (not already processed)
            // and enough time has passed since the last toast
            // Show toast for ALL users (including the one who submitted it)
            const now = Date.now();
            const timeSinceLastToast = now - lastToastTime;
            const minToastInterval = 2000; // 2 seconds minimum between toasts
            
            const shouldShowToast = isNewSuggestion && timeSinceLastToast > minToastInterval;
            
            if (shouldShowToast) {
              const username = newSuggestion.username || 'Unknown Player';
              const toastMessage = `${username} suggests: "${newSuggestion.message}"`;
              console.log(`[SCENARIO SELECTOR] Showing toast: ${toastMessage} (isHost: ${isHost})`);
              showToast(toastMessage, 'info'); // Show for 3 seconds (default)
              
              // Update all tracking mechanisms immediately
              lastProcessedSuggestionId.current = newSuggestion.id;
              setLastSeenSuggestionId(newSuggestion.id);
              setLastToastSuggestionId(newSuggestion.id);
              setLastToastTime(now);
              
              if (typeof window !== 'undefined' && initialRoomCode) {
                localStorage.setItem(`lastSeenSuggestionId_${initialRoomCode}`, newSuggestion.id);
                localStorage.setItem(`lastToastSuggestionId_${initialRoomCode}`, newSuggestion.id);
                console.log(`[SCENARIO SELECTOR] Saved both IDs to localStorage: ${newSuggestion.id}`);
              }
              
              console.log(`[SCENARIO SELECTOR] Marked toast as shown for suggestion: ${newSuggestion.id}`);
            } else {
              if (!isNewSuggestion) {
                console.log(`[SCENARIO SELECTOR] Skipping toast - same suggestion as last processed (isHost: ${isHost})`);
              } else {
                console.log(`[SCENARIO SELECTOR] Skipping toast - too soon since last toast (${timeSinceLastToast}ms < ${minToastInterval}ms) (isHost: ${isHost})`);
              }
            }
            
            // Note: lastSeenSuggestionId is now updated immediately when toast is shown
            // This ensures the persistent display tracking is always current
          }
          
          // Only keep the last suggestion for display
          const lastSuggestion = newSuggestions.length > 0 ? [newSuggestions[0]] : [];
          setRecentSuggestions(lastSuggestion);
        } else {
          console.error(`[SCENARIO SELECTOR] Failed to fetch suggestions, status: ${response.status}`);
        }
      } catch (error) {
        console.error('Failed to fetch suggestions:', error);
      }
    }, 3000);
    
    return () => {
      console.log(`[SCENARIO SELECTOR] Stopping polling for room ${initialRoomCode}`);
      clearInterval(interval);
      
      // Clean up localStorage when polling stops
      if (typeof window !== 'undefined' && initialRoomCode) {
        localStorage.removeItem(`lastSeenSuggestionId_${initialRoomCode}`);
        localStorage.removeItem(`lastToastSuggestionId_${initialRoomCode}`);
      }
      
      // Reset ref when polling stops
      lastProcessedSuggestionId.current = null;
    };
  }, [initialRoomCode]);

  // Load scenarios on component mount and when room code changes
  useEffect(() => {
    const loadScenarios = async () => {
      if (!initialRoomCode) return;
      
      try {
        console.log(`[SCENARIO SELECTOR] Loading scenarios for room ${initialRoomCode}`);
        const response = await fetch(`/game?roomCode=${encodeURIComponent(initialRoomCode)}`, {
          method: 'POST',
          body: new URLSearchParams({
            intent: 'getRoomScenarios',
            roomCode: initialRoomCode
          })
        });
        
        if (response.ok) {
          const data = await response.json();
          const scenarios = data.scenarios || [];
          
          console.log(`[SCENARIO SELECTOR] Loaded ${scenarios.length} scenarios from room ${initialRoomCode}`);
          
          if (scenarios.length > 0) {
            setDisplayedScenarios(scenarios);
            
            // If this is a non-host user and scenarios were loaded from persistence, show a subtle notification
            if (!isHost) {
              showToast(`Loaded ${scenarios.length} scenarios from room`, 'info');
            }
          }
        } else {
          console.error(`[SCENARIO SELECTOR] Failed to load scenarios, status: ${response.status}`);
        }
      } catch (error) {
        console.error('Failed to load scenarios:', error);
      }
    };

    loadScenarios();
  }, [initialRoomCode, isHost]);

  // Poll for new scenarios every 2 seconds for all users (including host)
  useEffect(() => {
    if (!initialRoomCode) return; // All users should poll for scenarios to ensure persistence
    
    console.log(`[SCENARIO SELECTOR] Starting scenario polling for non-host user in room ${initialRoomCode}`);
    
    const interval = setInterval(async () => {
      try {
        console.log(`[SCENARIO SELECTOR] Polling for scenarios in room ${initialRoomCode}`);
        const response = await fetch(`/game?roomCode=${encodeURIComponent(initialRoomCode)}`, {
          method: 'POST',
          body: new URLSearchParams({
            intent: 'getRoomScenarios',
            roomCode: initialRoomCode
          })
        });
        console.log(`[SCENARIO SELECTOR] Scenario polling response status: ${response.status}`);
        
        if (response.ok) {
          const data = await response.json();
          const newScenarios = data.scenarios || [];
          
          console.log(`[SCENARIO SELECTOR] Current scenarios: ${displayedScenarios?.length || 0}, New scenarios: ${newScenarios.length}`);
          
          // Check if we have new scenarios and update the display
          if (newScenarios.length > 0) {
            const wasEmpty = !displayedScenarios || displayedScenarios.length === 0;
            const isNewGeneration = displayedScenarios && newScenarios.length !== displayedScenarios.length;
            
            console.log(`[SCENARIO SELECTOR] Updating scenarios: wasEmpty=${wasEmpty}, isNewGeneration=${isNewGeneration}`);
            setDisplayedScenarios(newScenarios);
            
            // Show appropriate toast notification
            if (wasEmpty && isNewGeneration) {
              // Scenarios were loaded after being empty (page refresh or initial load)
              if (!isHost) {
                showToast(`Loaded ${newScenarios.length} scenarios from room`, 'info');
              }
            } else if (isNewGeneration) {
              // New scenarios were generated
              const toastMessage = `Host generated ${newScenarios.length} new scenarios!`;
              showToast(toastMessage, 'info');
            }
            // If scenarios exist and count hasn't changed, don't show toast (existing scenarios)
          }
        } else {
          console.error(`[SCENARIO SELECTOR] Failed to fetch scenarios, status: ${response.status}`);
        }
      } catch (error) {
        console.error('Failed to fetch scenarios:', error);
      }
    }, 2000); // Poll every 2 seconds for faster updates
    
    return () => {
      console.log(`[SCENARIO SELECTOR] Stopping scenario polling for room ${initialRoomCode}`);
      clearInterval(interval);
    };
  }, [initialRoomCode, isHost, displayedScenarios]);

  // Handle voting responses to update UI without refresh
  useEffect(() => {
    if (voteFetcher.data && voteFetcher.state === 'idle') {
      if (voteFetcher.data.success) {
        showToast(voteFetcher.data.message || 'Vote cast successfully!', 'success');
      } else if (voteFetcher.data.error) {
        showToast(voteFetcher.data.error, 'error');
      }
    }
  }, [voteFetcher.data, voteFetcher.state, showToast]);

  // Handle scenario regeneration when regenerate majority is reached
  useEffect(() => {
    if (regenerateMajority && isHost && roomCode) {
      console.log(`[SCENARIO SELECTOR] Regenerate majority reached, generating new scenarios for room ${roomCode}`);
      
      const formData = new FormData();
      formData.append('intent', 'generateScenarios');
      formData.append('duration', selectedDuration);
      formData.append('activeCharacter', JSON.stringify(activeCharacter));
      formData.append('partyCharacters', JSON.stringify(partyCharacters));
      formData.append('partySlots', JSON.stringify(partySlots));
      if (customPrompt.trim()) {
        formData.append('regenerationPrompt', customPrompt.trim());
      }
      formData.append('roomCode', roomCode);
      
      fetcher.submit(formData, { method: 'post', action: '/game' });
    }
  }, [regenerateMajority, isHost, roomCode, selectedDuration, activeCharacter, partyCharacters, partySlots, customPrompt]);

  // Handle scenario selection responses to redirect without refresh
  useEffect(() => {
    if (scenarioFetcher.data && scenarioFetcher.state === 'idle') {
      if (scenarioFetcher.data.redirect) {
        window.location.href = scenarioFetcher.data.redirect;
      } else if (scenarioFetcher.data.error) {
        showToast(scenarioFetcher.data.error, 'error');
      }
    }
  }, [scenarioFetcher.data, scenarioFetcher.state, showToast]);

  // Poll for real-time vote updates every 1 second
  useEffect(() => {
    if (!initialRoomCode) return;
    
    console.log(`[SCENARIO SELECTOR] Starting vote polling for room ${initialRoomCode}`);
    
    const interval = setInterval(async () => {
      try {
        console.log(`[SCENARIO SELECTOR] Polling for votes in room ${initialRoomCode}`);
        const response = await fetch(`/api/room/votes?roomCode=${encodeURIComponent(initialRoomCode)}`);
        console.log(`[SCENARIO SELECTOR] Vote polling response status: ${response.status}`);
        
        if (response.ok) {
          const data = await response.json();
          const voteUpdates = data.votes || [];
          
          console.log(`[SCENARIO SELECTOR] Received ${voteUpdates.length} vote updates`);
          
          // Update scenario votes if there are changes
          if (voteUpdates.length > 0) {
            console.log(`[POLLING] Received ${voteUpdates.length} vote updates:`, voteUpdates);
            console.log(`[POLLING] Current scenarioVotes before update:`, scenarioVotes);
            
            // Update local scenarioVotes state with the latest votes
            const updatedVotes = { ...scenarioVotes };
            voteUpdates.forEach(vote => {
              updatedVotes[vote.scenarioId] = (updatedVotes[vote.scenarioId] || 0) + 1;
            });
            console.log(`[POLLING] Updated scenarioVotes:`, updatedVotes);
            setScenarioVotes(updatedVotes);
            
            // Update userVotes state based on the new vote data
            const updatedUserVotes = { ...userVotes };
            voteUpdates.forEach(vote => {
              if (vote.slotIndex !== undefined) {
                updatedUserVotes[vote.slotIndex] = vote.scenarioId;
              }
            });
            console.log(`[POLLING] Updated userVotes:`, updatedUserVotes);
            setUserVotes(updatedUserVotes);
            
            // Refresh scenarios to get latest vote counts and userVotes
            const scenariosResponse = await fetch(`/api/room/scenarios?roomCode=${encodeURIComponent(initialRoomCode)}`);
            if (scenariosResponse.ok) {
              const scenariosData = await scenariosResponse.json();
              const updatedScenarios = scenariosData.scenarios || [];
              
              if (updatedScenarios.length > 0) {
                setDisplayedScenarios(updatedScenarios);
                
                // Show notification for new votes
                const newVotes = voteUpdates.filter(vote => 
                  new Date(vote.timestamp) > new Date(lastVoteTime)
                );
                
                if (newVotes.length > 0) {
                  const voteMessages = newVotes.map(vote => {
                    const scenario = updatedScenarios.find(s => s.id === vote.scenarioId);
                    const scenarioTitle = scenario ? scenario.title : 'Unknown Scenario';
                    return `${vote.username} voted for "${scenarioTitle}"`;
                  });
                  
                  if (voteMessages.length > 0) {
                    showToast(`New votes: ${voteMessages.join(', ')}`, 'info');
                  }
                }
                
                // Update last vote time
                if (voteUpdates.length > 0) {
                  const latestVote = voteUpdates.reduce((latest, current) => 
                    new Date(current.timestamp) > new Date(latest.timestamp) ? current : latest
                  );
                  setLastVoteTime(latestVote.timestamp);
                }
              }
            }
          }
        } else {
          console.error(`[SCENARIO SELECTOR] Failed to fetch votes, status: ${response.status}`);
        }
      } catch (error) {
        console.error('Failed to fetch votes:', error);
      }
    }, 1000); // Poll every 1 second for real-time updates
    
    return () => {
      console.log(`[SCENARIO SELECTOR] Stopping vote polling for room ${initialRoomCode}`);
      clearInterval(interval);
    };
  }, [initialRoomCode, lastVoteTime, scenarioVotes, userVotes]);
  
  // Find the scenario with the most votes
  const winningScenario = currentScenarios?.length ? currentScenarios.reduce((prev, current) => {
    const prevVotes = scenarioVotes[prev.id] || 0;
    const currentVotes = scenarioVotes[current.id] || 0;
    return currentVotes > prevVotes ? current : prev;
  }) : null;
  
  // Get all vote counts to check for ties
  const allVoteCounts = currentScenarios?.map(s => scenarioVotes[s.id] || 0) || [];
  const maxVotes = Math.max(...allVoteCounts, 0);
  const tiedScenarios = currentScenarios?.filter(s => (scenarioVotes[s.id] || 0) === maxVotes) || [];
  const hasClearWinner = tiedScenarios.length === 1 && maxVotes > 0;
  
  // Determine if we should show "Start Your Adventure" button
  const shouldShowStartAdventure: boolean = allHaveVoted && !regenerateMajority && hasClearWinner;
  
  // Tiebreaker logic for scenarios with no clear winner
  const needsTiebreaker: boolean = allHaveVoted && !regenerateMajority && !hasClearWinner && maxVotes > 0;
  
  // Debug logging
  console.log('Voting debug:', {
    allHaveVoted,
    regenerateMajority,
    hasClearWinner,
    maxVotes,
    tiedScenarios: tiedScenarios.length,
    needsTiebreaker,
    scenarioVotes,
    userVotes
  });

  

  // Automatically submit when all dice rolls are complete
  useEffect(() => {
    if (Object.keys(diceRolls).length === totalActiveSlots && totalActiveSlots > 0 && !diceRollComplete) {
      const timer = setTimeout(() => {
        setDiceRollComplete(true);
      }, 2000); // 2 second delay to show results before auto-submit
      
      return () => clearTimeout(timer);
    }
  }, [diceRolls, totalActiveSlots, diceRollComplete]);

  // If countdown is showing, display countdown overlay
  if (showCountdown) {
    return (
      <div className="min-h-screen w-full flex items-center justify-center p-4 bg-gray-900">
        <div className="flex flex-col items-center justify-center">
          <div className="text-center">
            <h1 className="text-6xl font-medieval text-red-500 mb-8">Get Ready!</h1>
            <div className="text-9xl font-bold text-yellow-400 mb-8 animate-pulse">
              {countdown}
            </div>
            <p className="text-2xl text-gray-300">Prepare your adventure...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen w-full flex items-center justify-center p-4 bg-gray-900">
      <div className="w-full max-w-4xl bg-black bg-opacity-70 p-8 rounded-lg border border-gray-700 shadow-lg text-white">
        
        {/* Host Controls */}
        <div className="mb-6 flex justify-between items-center">
          <div>
            {isHost && roomCode && (
              <button 
                onClick={async () => {
                  try {
                    // Reset room status back to lobby
                    const formData = new FormData();
                    formData.append('intent', 'resetRoomStatus');
                    formData.append('roomCode', roomCode);
                    
                    const response = await fetch('/game', {
                      method: 'POST',
                      body: formData
                    });
                    
                    if (response.ok) {
                      console.log(`[SCENARIO SELECTOR] Room ${roomCode} status reset to lobby by host`);
                    }
                  } catch (error) {
                    console.error('Failed to reset room status:', error);
                  }
                  
                  // Navigate back to room
                  window.location.href = `/game?roomCode=${roomCode}`;
                }}
                className="bg-red-700 hover:bg-red-600 text-white font-bold py-3 px-6 rounded-lg transition duration-200 ease-in-out shadow-lg hover:shadow-xl"
              >
                ← Back to Room Setup
              </button>
            )}
          </div>
          <div className="text-gray-400 text-sm">
            {roomCode && `Room: ${roomCode}`}
          </div>
        </div>

        <h2 className="text-5xl font-medieval text-red-500 text-center mb-8">Choose Your Adventure!</h2>

        <div className="mb-8">
          <h3 className="text-3xl font-medieval text-red-400 mb-4">Campaign Duration & Theme</h3>
          <div className="flex flex-col gap-4">
            <div className="flex flex-col sm:flex-row gap-4 items-center">
              <label htmlFor="duration-select" className="text-lg text-gray-300 w-full sm:w-auto">Duration:</label>
              <select
                id="duration-select"
                value={selectedDuration}
                onChange={handleDurationChange}
                className="flex-grow p-3 bg-gray-700 text-white rounded-md border border-gray-600 focus:outline-none focus:border-red-500 text-lg"
                disabled={isGenerating}
              >
                <option value="Short">Short Campaign (30 min - 1 hr)</option>
                <option value="Medium">Medium Campaign (1 hr - 3 hrs)</option>
                <option value="Long">Long Campaign (3 hrs+)</option>
              </select>
            </div>

            <textarea
              className="w-full p-3 bg-gray-700 border border-gray-600 rounded-md text-gray-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-red-500 text-lg"
              rows={3}
              placeholder="Optional: Describe a custom theme or setting (e.g., 'A quest focused on political intrigue in a desert city'). This will influence all 4 generated scenarios. You can also use this field to suggest scenarios that will be broadcast to all players."
              value={customPrompt}
              onChange={(e) => setCustomPrompt(e.target.value)}
              disabled={isGenerating}
            ></textarea>

            {isHost ? (
              <button
                onClick={() => {
                  if (!activeCharacter) {
                    alert("Active character data is missing. Cannot generate scenarios.");
                    return;
                  }
                  const formData = new FormData();
                  formData.append('intent', 'generateScenarios');
                  formData.append('duration', selectedDuration);
                  formData.append('activeCharacter', JSON.stringify(activeCharacter));
                  formData.append('partyCharacters', JSON.stringify(partyCharacters));
                  formData.append('partySlots', JSON.stringify(partySlots));
                  if (customPrompt.trim()) {
                    formData.append('regenerationPrompt', customPrompt.trim());
                  }
                  if (roomCode) {
                    formData.append('roomCode', roomCode);
                  }
                  fetcher.submit(formData, { method: 'post', action: '/game' });
                }}
                className="bg-red-700 hover:bg-red-600 text-white font-bold py-3 px-6 rounded-md text-xl transition duration-200 ease-in-out disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={isGenerating}
              >
                {isGenerating ? 'Generating Scenarios...' : partySlots.length > 1 && regenerateVoteCount > 0 ? `Generate 4 Adventure Scenarios (${regenerateVoteCount}/${totalActiveSlots} votes for regeneration)` : 'Generate 4 Adventure Scenarios'}
              </button>
            ) : (
              <div className="space-y-4">
                <button
                  onClick={handleSuggestScenario}
                  className="bg-blue-700 hover:bg-blue-600 text-white font-bold py-3 px-6 rounded-md text-xl transition duration-200 ease-in-out"
                >
                  Broadcast Suggestion
                </button>
                <p className="text-gray-400 text-sm">Wait for the host to generate scenarios or broadcast your idea to the group using the field above</p>
              </div>
            )}
            
            {/* DEBUG INFO: Show host status and room details */}
            <div className="mt-4 p-3 bg-gray-700 rounded-md border border-gray-600">
              <div className="text-sm font-semibold text-gray-300 mb-2">Debug Info:</div>
              <div className="text-xs text-gray-400 space-y-1">
                <div>isHost: <span className={isHost ? "text-green-400 font-bold" : "text-red-400 font-bold"}>{isHost.toString()}</span></div>
                <div>roomCode: <span className="text-yellow-400">{roomCode || 'null'}</span></div>
                <div>partySlots.length: <span className="text-yellow-400">{partySlots.length}</span></div>
                <div>currentUserId: <span className="text-yellow-400">{currentUserId || 'null'}</span></div>
              </div>
            </div>
          </div>
        </div>

        {/* Host Controls - Always visible for host */}
        {isHost && (
          <div className="mb-6 flex justify-between items-center border-t border-gray-600 pt-6">
            <div>
              <button 
                onClick={async () => {
                  try {
                    const formData = new FormData();
                    formData.append('intent', 'resetRoomStatus');
                    formData.append('roomCode', roomCode || '');
                    
                    const response = await fetch('/game', {
                      method: 'POST',
                      body: formData
                    });
                    
                    if (response.ok) {
                      console.log(`[SCENARIO SELECTOR] Room ${roomCode} status reset to lobby by host before generation`);
                    }
                  } catch (error) {
                    console.error('Failed to reset room status before generation:', error);
                  }
                  
                  // Navigate back to room
                  window.location.href = `/game?roomCode=${roomCode}`;
                }}
                className="bg-red-700 hover:bg-red-600 text-white font-bold py-3 px-6 rounded-lg transition duration-200 ease-in-out shadow-lg hover:shadow-xl"
              >
                ← Back to Room Setup
              </button>
            </div>
            <div className="text-gray-400 text-sm">
              {roomCode && `Room: ${roomCode}`}
            </div>
          </div>
        )}

        {isGenerating ? (
          <div className="text-center text-red-300 text-2xl mt-8">
            <p>Summoning the spirits of adventure...</p>
            <p>Please wait while scenarios are generated.</p>
          </div>
        ) : fetcher.data?.error ? (
          <div className="text-center text-red-500 text-xl mt-8">
            <p>Error: {fetcher.data.error}</p>
            <p>Please try again or simplify your custom prompt.</p>
          </div>
        ) : currentScenarios && currentScenarios.length > 0 ? (
          <div className="mt-8">
            <h3 className="text-3xl font-medieval text-red-400 text-center mb-6">Available Scenarios</h3>
            
            {/* Party voting info */}
            {partySlots.length > 1 && (
              <div className="text-center mb-6 text-lg text-yellow-300">
                <p>Votes Cast: {totalVotesCast}/{totalActiveSlots} | Your Votes: {userVotesCast}/{userActiveSlots}</p>
                <p className="text-sm text-gray-400">You control {userActiveSlots} slot(s): {userSlotIndices.join(', ')}</p>
              </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {currentScenarios.map((scenario) => {
                const voteCount = scenarioVotes[scenario.id] || 0;
                return (
                  <div key={scenario.id} className="bg-gray-800 p-5 rounded-lg border border-gray-600 flex flex-col justify-between relative">
                    {/* Vote count badge - top right corner */}
                    {partySlots.length > 1 && (
                      <div className="absolute top-3 right-3 bg-yellow-400 text-black font-bold rounded-full w-8 h-8 flex items-center justify-center text-sm">
                        {voteCount}
                      </div>
                    )}
                    
                    {/* Show detailed voting information */}
                    {partySlots.length > 1 && (
                      <div className="mt-2 space-y-1">
                        {/* Show vote count and who voted */}
                        <div className="flex items-center justify-between">
                          <span className="text-xs text-gray-400">Votes: {voteCount}</span>
                          <span className="text-xs text-green-400">You have {userActiveSlots - userVotesCast} votes left</span>
                        </div>
                        
                        {/* Show who voted for this scenario with timestamps */}
                        <div className="text-xs text-gray-400">
                          {scenario.userVotes && scenario.userVotes.length > 0 ? (
                            scenario.userVotes.map((vote, index) => {
                              const timeAgo = new Date(vote.timestamp).toLocaleTimeString();
                              return (
                                <span key={index} className={`inline-block px-2 py-1 rounded mr-1 mb-1 ${
                                  vote.userId === currentUserId 
                                    ? 'bg-green-100 text-green-800 border border-green-300' 
                                    : 'bg-blue-100 text-blue-800'
                                }`}>
                                  {vote.username} (Slot {vote.slotIndex}) • {timeAgo}
                                </span>
                              );
                            })
                          ) : (
                            <span className="text-gray-500">No votes yet</span>
                          )}
                        </div>
                      </div>
                    )}
                    
                    <div>
                      <h4 className="text-2xl font-medieval text-green-400 mb-2 pr-10">{scenario.title}</h4>
                      <p className="text-gray-300 text-sm mb-2"><strong>Environment:</strong> {scenario.surrounding}</p>
                      <p className="text-gray-300 text-sm mb-4"><strong>Objective:</strong> {scenario.objective}</p>
                      {scenario.possibleEncounters && scenario.possibleEncounters.length > 0 && (
                        <div className="mb-2">
                          <strong className="text-gray-400">Encounters:</strong>
                          <ul className="list-disc list-inside text-xs text-gray-300">
                            {scenario.possibleEncounters.slice(0, 3).map((encounter: string, index: number) => (
                              <li key={index}>{encounter}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {scenario.possibleEnemies && scenario.possibleEnemies.length > 0 && (
                        <div className="mb-2">
                          <strong className="text-gray-400">Enemies:</strong>
                          <ul className="list-disc list-inside text-xs text-gray-300">
                            {scenario.possibleEnemies.slice(0, 3).map((enemy: string, index: number) => (
                              <li key={index}>{enemy}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {scenario.bossFight && (
                        <div className="mb-2">
                          <strong className="text-gray-400">Boss:</strong>
                          <p className="text-xs text-gray-300">{scenario.bossFight.name} ({scenario.bossFight.description})</p>
                        </div>
                      )}
                    </div>

                    {partySlots.length > 1 ? (
                      <button
                        onClick={() => {
                          // Find first unvoted slot owned by current user and vote
                          for (let slotIndex of userSlotIndices) {
                            if (!userVotes[slotIndex]) {
                              handleVoteScenario(slotIndex, scenario.id);
                              return;
                            }
                          }
                        }}
                        disabled={userHasCompletedVoting}
                        className={`mt-4 w-full font-bold py-2 px-4 rounded-md transition duration-200 ease-in-out ${
                          userVotesCast > 0
                            ? 'bg-yellow-600 text-white'
                            : userHasCompletedVoting
                            ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
                            : 'bg-blue-700 hover:bg-blue-600 text-white'
                        }`}
                      >
                        {userVotesCast > 0 ? `✓ Voted (${userVotesCast}/${userActiveSlots})` : 'Vote for This Adventure'}
                      </button>
                    ) : (
                      <button
                        onClick={() => handleSelectScenario(scenario)}
                        className="mt-4 w-full bg-green-700 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-md transition duration-200 ease-in-out"
                      >
                        Start This Adventure
                      </button>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Regenerate scenarios option for multi-party */}
            {partySlots.length > 1 && (
              <div className="mt-8 text-center">
                <button
                  onClick={() => {
                    // Find first unvoted slot owned by current user and vote to regenerate
                    for (let slotIndex of userSlotIndices) {
                      if (!userVotes[slotIndex]) {
                        handleVoteRegenerate(slotIndex);
                        return;
                      }
                    }
                  }}
                  disabled={userHasCompletedVoting}
                  className={`font-bold py-3 px-6 rounded-lg transition duration-200 ease-in-out ${
                    regenerationVotes > 0
                      ? 'bg-orange-600 text-white'
                      : userHasCompletedVoting
                      ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
                      : 'bg-orange-700 hover:bg-orange-600 text-white'
                  }`}
                >
                  {regenerationVotes > 0 ? `✓ You Voted to Regenerate` : `Vote to Regenerate Scenarios`}
                </button>
              </div>
            )}

            {/* "Start Your Adventure" button when everyone has voted */}
            {shouldShowStartAdventure && (
              <div className="mt-8 text-center">
                <button
                  onClick={() => {
                    if (winningScenario) {
                      handleSelectScenario(winningScenario);
                    }
                  }}
                  className="bg-green-700 hover:bg-green-600 text-white font-bold py-4 px-8 rounded-lg transition duration-200 ease-in-out text-2xl"
                >
                  🚀 Start Your Adventure!
                </button>
                
                {winningScenario && (
                  <div className="mt-4 p-4 bg-green-900 bg-opacity-30 rounded-lg border border-green-600">
                    <h4 className="text-lg font-semibold text-green-400 mb-2">Selected Scenario:</h4>
                    <p className="text-green-300">{winningScenario.title}</p>
                    <p className="text-sm text-green-400 mt-1">With {scenarioVotes[winningScenario.id] || 1} vote(s)</p>
                  </div>
                )}
              </div>
            )}
            
            {/* Regeneration button when majority votes to regenerate */}
            {regenerateMajority && (
              <div className="mt-8 text-center">
                <button
                  onClick={() => {
                    if (!activeCharacter) {
                      alert("Active character data is missing. Cannot generate scenarios.");
                      return;
                    }
                    const formData = new FormData();
                    formData.append('intent', 'generateScenarios');
                    formData.append('duration', selectedDuration);
                    formData.append('activeCharacter', JSON.stringify(activeCharacter));
                    formData.append('partyCharacters', JSON.stringify(partyCharacters));
                    formData.append('partySlots', JSON.stringify(partySlots));
                    if (customPrompt.trim()) {
                      formData.append('regenerationPrompt', customPrompt.trim());
                    }
                    fetcher.submit(formData, { method: 'post', action: '/game' });
                  }}
                  disabled={isGenerating}
                  className="bg-purple-700 hover:bg-purple-600 text-white font-bold py-4 px-8 rounded-lg transition duration-200 ease-in-out text-lg"
                >
                  {isGenerating ? 'Generating New Scenarios...' : `🔄 Generate New Scenarios (Majority Voted)`}
                </button>
                
                <div className="mt-2 text-purple-300">
                  Majority ({regenerateVoteCount}/{totalActiveSlots}) voted to regenerate scenarios
                </div>
              </div>
            )}
            
            {/* Tie-breaking dice roll for unresolved votes */}
            {needsTiebreaker && !showDiceRoll && (
              <div className="mt-8 text-center">
                <div className="mb-4 p-4 bg-yellow-900 bg-opacity-30 rounded-lg border border-yellow-600">
                  <h4 className="text-lg font-semibold text-yellow-400">Tie-Breaking Required</h4>
                  <p className="text-yellow-300">No scenario has a clear majority. Roll dice to determine the winner!</p>
                </div>
                
                <div className="space-y-4">
                  <button
                    onClick={handleTiebreakerDiceRoll}
                    className="bg-yellow-700 hover:bg-yellow-600 text-white font-bold py-3 px-6 rounded-lg transition duration-200 ease-in-out text-xl"
                  >
                    🎲 Roll Dice to Break Tie!
                  </button>
                  
                  {/* Debug button to test dice loading */}
                  <div className="mt-4">
                    <button
                      onClick={() => {
                        console.log('Testing dice library loading...');
                        console.log('DICE object:', typeof window.DICE);
                        if (window.DICE) {
                          console.log('DICE.dice_box:', typeof window.DICE.dice_box);
                        }
                      }}
                      className="bg-gray-700 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded text-sm"
                    >
                      Debug Dice Loading
                    </button>
                    
                    {/* Manual dice roll test */}
                    <button
                      onClick={() => {
                        console.log('Manual dice roll test...');
                        setShowDiceRoll(true);
                        setDiceRolls({0: 15, 1: 8}); // Simulate results
                        setDiceRollComplete(true);
                      }}
                      className="bg-green-700 hover:bg-green-600 text-white font-bold py-2 px-4 rounded text-sm ml-2"
                    >
                      Test Dice Results
                    </button>
                  </div>
                </div>
              </div>
            )}
            
            {/* Dice rolling interface */}
            {showDiceRoll && (
              <div className="mt-8">
                <div className="text-center mb-6">
                  <h3 className="text-3xl font-medieval text-yellow-400 mb-2">🎲 Rolling for Destiny...</h3>
                  <p className="text-lg text-yellow-300">Each player rolls a die to break the tie</p>
                </div>
                
                {isInitializingDice && (
                  <div className="mb-4 text-center">
                    <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-yellow-400"></div>
                    <p className="mt-2 text-yellow-300 text-sm">Initializing dice rolling...</p>
                  </div>
                )}
                
                {diceState && (
                  <DiceRoller3D
                    players={diceState.players.map(player => ({
                      slotIndex: player.slotIndex,
                      characterName: player.characterName,
                      userId: player.userId,
                      hasRolled: diceState.rolls[player.slotIndex] !== undefined,
                      result: diceState.rolls[player.slotIndex]
                    }))}
                    currentUserId={currentUserId}
                    diceState={diceState}
                    onPlayerRollComplete={onPlayerRollComplete}
                  />
                )}
                
                {!diceState && !isInitializingDice && (
                  <div className="text-center text-gray-400">
                    Waiting for dice rolling to start...
                  </div>
                )}
                
                {diceState && diceState.status === 'completed' && (
                  <div className="text-center">
                    <div className="bg-green-600 text-white font-bold py-3 px-6 rounded-lg inline-block mb-4">
                      Winner: {diceState.players[diceState.winner!]?.characterName} with {diceState.rolls[diceState.winner!]}!
                    </div>
                    <button
                      onClick={() => {
                        setShowDiceRoll(false);
                        setDiceRolls({});
                        setDiceRollComplete(false);
                      }}
                      className="bg-green-600 hover:bg-green-500 text-white font-bold py-2 px-4 rounded"
                    >
                      Continue
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        ) : currentScenarios && currentScenarios.length === 0 && !isGenerating ? (
          <div className="text-center text-gray-400 text-xl mt-8">
            <p>Select a campaign duration and click Generate 4 Adventure Scenarios to begin!</p>
          </div>
        ) : (
          <div className="text-center text-gray-400 text-xl mt-8">
            <p>Loading scenarios...</p>
          </div>
        )}
      </div>
      
      {roomCode && (
        <div className="mt-6 p-4 bg-gray-700 rounded-lg border border-gray-600">
          <h4 className="text-lg font-semibold text-gray-300 mb-3">Recent Suggestions</h4>
          {recentSuggestions.length === 0 ? (
            <p className="text-gray-400">No suggestions yet. Be the first to suggest a scenario!</p>
          ) : (
            <div className="space-y-2">
              {recentSuggestions.map((suggestion) => (
                <div key={suggestion.id} className="bg-gray-800 p-3 rounded border border-gray-600">
                  <div className="flex justify-between items-start">
                    <div>
                      <span className="text-yellow-400 font-semibold">{suggestion.username}</span>
                      <span className="text-gray-400 text-sm ml-2">
                        {new Date(suggestion.created_at).toLocaleTimeString()}
                      </span>
                    </div>
                  </div>
                  <p className="text-gray-300 mt-1">"{suggestion.message}"</p>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
      
      </div>
    );
  }
